networks:
  default:
    external: true
    name: proxy-net

# https://sing-box.sagernet.org/installation/docker/
services:
  sing-box-app:
    image: ghcr.io/minlaxz/nekohasekai-app:main
    container_name: sing-box-app
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - type: bind
        source: ./server.json
        target: /home/app/my-config.json
    env_file:
      - .env

  sing-box:
    image: ghcr.io/minlaxz/nekohasekai-singbox:main
    container_name: sing-box
    restart: unless-stopped
    ports:
      - "2001:2001/udp"
      - "2002:2002/udp"
      - "2003:2003/udp"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ./server.json:/etc/sing-box/config.json:ro
      - ./certs:/certs:ro
    # this entrypoint is using /usr/bin/sing-box
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
